export enum BootLogType {
  OK      = '  OK  ',
  INFO    = ' INFO ',
  SYSTEM  = 'SYSTEM',
  WARN    = ' WARN ',
}

export const bootLog: (() => [BootLogType, string])[] = [
  () => [BootLogType.OK, 'AetherOS version 6.1.30 (user@aether-machine) (gcc version 12.2.0) #1 SMP ' + new Date().toUTCString()],
  () => [BootLogType.INFO, 'Command line: BOOT_IMAGE=/boot/vmlinuz-6.1.30 root=/dev/sda1 ro quiet splash'],
  () => [BootLogType.OK, 'x86_64: Initializing CPU architecture'],
  () => [BootLogType.INFO, 'Memory: 16384000K/16777216K available (12288K kernel code, 4096K rwdata, 2048K rodata, 8192K init)'],
  () => [BootLogType.INFO, 'Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.1.30 root=/dev/sda1 ro quiet splash'],
  () => [BootLogType.OK, 'DMI: TSRC Systems/TSRC-One, BIOS TSRC-1.4.5 12/06/2024'],
  () => [BootLogType.INFO, 'Secure Boot: Disabled'],
  () => [BootLogType.OK, 'Virtualization: VSM support enabled'],
  () => [BootLogType.OK, 'x86/CPU: VEX-9 HyperCore Architecture detected'],
  () => [BootLogType.INFO, 'x86/CPU: TSRC Celestium™ NX9-4100 @ 3.20GHz (family: 10, model: 49, stepping: 7)'],

  () => [BootLogType.OK, 'MTRR: Memory Type Range Registers enabled'],
  () => [BootLogType.INFO, 'ACPI: Core revision 20230520'],
  () => [BootLogType.OK, 'ACPI: Power Button [PWRB]'],
  () => [BootLogType.OK, 'ACPI: Lid Switch [LID0]'],
  () => [BootLogType.INFO, 'ACPI: Thermal Zone [THRM] (28 C)'],
  () => [BootLogType.INFO, 'PCI: MMCONFIG at [mem 0xe0000000-0xe3ffffff] reserved in region 0'],
  () => [BootLogType.INFO, 'PCI: Probing PCI hardware'],
  () => [BootLogType.OK, 'PCI: Using host bridge windows from ACPI'],
  () => [BootLogType.INFO, 'Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled'],

  () => [BootLogType.INFO, 'usbcore: registered new interface driver usbfs'],
  () => [BootLogType.INFO, 'usbcore: registered new interface driver hub'],
  () => [BootLogType.OK, 'usbcore: registered new device driver usb'],
  () => [BootLogType.INFO, 'ehci_hcd: USB 2.0 \'Enhanced\' Host Controller (EHCI) Driver'],
  () => [BootLogType.OK, 'ohci_hcd: USB 1.1 \'Open\' Host Controller (OHCI) Driver'],
  () => [BootLogType.OK, 'uhci_hcd: USB Universal Host Controller Interface driver'],

  () => [BootLogType.INFO, 'ata1: SATA link up 6.0 Gbps (SStatus 133 SControl 300)'],
  () => [BootLogType.INFO, 'ata1.00: ATA-12: TSRC QuantaDrive 512G-X, QDX4.02, max UDMA/133'],
  () => [BootLogType.INFO, 'ata1.00: 976773168 sectors, multi 16: LBA48 NCQ (depth 32)'],
  () => [BootLogType.OK, 'ata1.00: configured for UDMA/133'],
  () => [BootLogType.OK, 'scsi 0:0:0:0: Direct-Access     TSRC      QuantaDrive 512G-X PQ: 0 ANSI: 5'],

  () => [BootLogType.INFO, 'tsrcgfx 0000:00:02.0: enabling device (0006 -> 0007)'],
  () => [BootLogType.OK,  '[drm] Initialized tsrcgfx 1.6.0 20230520 for 0000:00:02.0 on minor 0'],
  () => [BootLogType.OK, 'fbcon: tsrcgfxfb (fb0) is primary device'],
  () => [BootLogType.OK, 'Console: switching to colour frame buffer device 1920x1080'],
  () => [BootLogType.OK, 'tsrcgfx 0000:00:02.0: fb0: tsrcgfxfb frame buffer device'],

  () => [BootLogType.INFO, 'tsrce-net: TSRC® HyperNet Driver - 1.2.3'],
  () => [BootLogType.INFO, 'tsrce-net: Copyright(c) 2024 TSRC Corporation'],
  () => [BootLogType.OK, 'tsrce-net 0000:00:19.0: irq 28 for MSI/MSI-X'],
  () => [BootLogType.OK, 'tsrce-net 0000:00:19.0 eth0: (PCI Express) 44:6a:78:9b:cc:dd'],
  () => [BootLogType.OK, 'tsrce-net 0000:00:19.0 eth0: TSRC HyperNet Connection'],

  () => [BootLogType.OK, 'VFS: Mounted root (ext4 filesystem) readonly on device 8:1.'],
  () => [BootLogType.OK, 'devtmpfs: mounted'],
  () => [BootLogType.OK, 'Freeing unused kernel memory: 8192K'],
  () => [BootLogType.OK, 'Write protecting the kernel read-only data: 12288K'],
  () => [BootLogType.OK, 'Run /sbin/init as init proces'],
  () => [BootLogType.OK, 'RNG: Initializing hardware random number generator (HWRNG)...'],
  () => [BootLogType.OK, 'RNG: TSRC QuantaSecure Module detected, entropy pool seeded.'],
  () => [BootLogType.OK, 'TPM: TSRC TPM 3.0 device initialized (firmware v3.2.1, rev: 17)'],
  () => [BootLogType.OK, 'PCI: Using ACPI for IRQ routing'],
  () => [BootLogType.OK, 'TSRC HyperCooling: Initializing advanced thermal management'],
  () => [BootLogType.INFO, 'TSRC HyperCooling: CPU core temps: 34°C, 35°C, 33°C, 36°C'],
  () => [BootLogType.INFO, 'TSRC HyperCooling: GPU temp: 40°C'],
  () => [BootLogType.OK, 'TSRC HyperCooling: System cooling thresholds set to 75°'],

  () => [BootLogType.INFO, 'NUMA: Node 0/1 available (8 CPUs, 16GB memory)'],
  () => [BootLogType.OK, 'NUMA: Initializing memory mappings for node 0'],
  () => [BootLogType.OK, 'NUMA: Initializing memory mappings for node 1'],

  () => [BootLogType.INFO, 'scsi 1:0:0:0: Direct-Access TSRC QuantaDrive 2TB-P NX PQ: 0 ANSI: 6'],
  () => [BootLogType.OK, 'sd 1:0:0:0: [sdb] 3907029168 512-byte logical blocks: (2.00 TB/1.82 TiB)'],
  () => [BootLogType.INFO, 'sd 1:0:0:0: [sdb] Write Protect is off'],
  () => [BootLogType.INFO, 'sd 1:0:0:0: [sdb] Mode Sense: 45 00 00 00'],
  () => [BootLogType.WARN, 'sd 1:0:0:0: [sdb] No Caching mode page found'],
  () => [BootLogType.OK, 'sd 1:0:0:0: [sdb] Assuming drive cache: write through\n sdb: sdb1'],
  () => [BootLogType.OK, 'sdb: sdb1'],
  () => [BootLogType.OK, 'sd 1:0:0:0: [sdb] Attached SCSI dis'],

  () => [BootLogType.OK, 'tsrc-audio: TSRC QuantumSound™ Audio Driver loaded'],
  () => [BootLogType.INFO, 'tsrc-audio: Found QuantumSound™ Wave-X chip, version 1.3'],

  () => [BootLogType.OK, 'ALSA: Initializing soundcard 0 with 8 output channels, 2 input channels'],
  () => [BootLogType.OK, 'ALSA: Setting default sample rate to 48kH'],

  () => [BootLogType.OK, 'tsrce-net 0000:00:19.0 eth0: Link is up - 1Gbps Full Duplex'],
  () => [BootLogType.OK, 'tsrce-net 0000:00:19.0 eth0: Enabling Jumbo Frames (MTU 9000)'],
  () => [BootLogType.OK, 'tsrce-net 0000:00:19.0 eth0: IPv6 support enable'],

  () => [BootLogType.OK, 'tsrcgfx 0000:00:02.0: Enabling ray-tracing extensions'],
  () => [BootLogType.OK, 'tsrcgfx 0000:00:02.0: HDR support enabled (10-bit color depth)'],
  () => [BootLogType.OK, 'tsrcgfx 0000:00:02.0: Vulkan API 1.3.2 detected and initialize'],

  () => [BootLogType.OK, 'usb 1-1: new high-speed USB device number 2 using ehci-pci'],
  () => [BootLogType.OK, 'usb 1-1: New USB device found, idVendor=1abc, idProduct=1234'],
  () => [BootLogType.OK, 'usb 1-1: Product: TSRC SecureKey 4.0'],
  () => [BootLogType.OK, 'usbcore: registered new interface driver usbhid'],
  () => [BootLogType.OK, 'usbhid: USB HID core drive'],

  () => [BootLogType.SYSTEM, 'systemd[1]: Starting TSRC Power Management...'],
  () => [BootLogType.SYSTEM, 'systemd[1]: Starting Time Synchronization...'],
  () => [BootLogType.SYSTEM, 'systemd[1]: Starting Display Manager...'],
  () => [BootLogType.SYSTEM, 'systemd[1]: Starting Network Time Service...'],
  () => [BootLogType.OK, 'systemd[1]: Reached target Multi-User System.'],
]
export const shutdownLog: (() => [BootLogType, string])[] = [
  () => [BootLogType.OK, 'Stopping TSRC AI-Assisted Daemon...'],
  () => [BootLogType.OK, 'Stopping Network Manager...'],
  () => [BootLogType.OK, 'Stopping Time Synchronization...'],
  () => [BootLogType.OK, 'Unmounting filesystems...'],
  () => [BootLogType.INFO, 'Saving session state to /var/aether/session-state...'],
  () => [BootLogType.OK, 'Session state saved successfully.'],
  () => [BootLogType.OK, 'Stopping Display Manager...'],
  () => [BootLogType.OK, 'Deactivating TSRC QuantumSound™ Wave-X Audio...'],
  () => [BootLogType.INFO, 'Closing all active audio streams... Done.'],
  () => [BootLogType.INFO, 'Powering down TSRC HyperNet interface (eth0).'],
  () => [BootLogType.OK, 'Network interface eth0 is now offline.'],
  () => [BootLogType.OK, 'Disabling Ray-Tracing and HDR on GPU...'],
  () => [BootLogType.INFO, 'TSRC Celestium NX9 GPU has entered low-power mode.'],
  () => [BootLogType.OK, 'Flushing disk buffers...'],
  () => [BootLogType.OK, 'All disks safely unmounted.'],
  
  () => [BootLogType.OK, 'Stopping remaining user-space services...'],
  () => [BootLogType.OK, 'Stopping TSRC HyperCooling module...'],
  () => [BootLogType.OK, 'CPU cores entering idle state...'],
  () => [BootLogType.INFO, 'TSRC Celestium NX9 temperatures: Core 0: 27°C, Core 1: 28°C, GPU: 35°C.'],
  () => [BootLogType.OK, 'ACPI system state transitioning to S5 (power-off).'],
  
  () => [BootLogType.INFO, 'Writing final kernel messages to /var/log/aetheros/shutdown.log...'],
  () => [BootLogType.INFO, 'TSRC SecureKey 4.0 removed safely.'],
  () => [BootLogType.INFO, 'Disabling hardware RNG...'],
  () => [BootLogType.OK, 'Hardware RNG stopped.'],
  () => [BootLogType.INFO, 'TPM module entering secure standby mode...'],
  () => [BootLogType.OK, 'TPM module status: Standby.'],
  
  () => [BootLogType.INFO, 'Synchronizing CPU caches...'],
  () => [BootLogType.OK, 'CPU caches synchronized.'],
  () => [BootLogType.OK, 'Disabling interrupts...'],
  () => [BootLogType.OK, 'Shutting down AetherOS kernel subsystems...'],
  
  () => [BootLogType.SYSTEM, 'System halted. Powering off...'],
  () => [BootLogType.SYSTEM, 'Goodbye from AetherOS. Thank you for trusting TSRC technology.'],
  () => [BootLogType.SYSTEM, 'Powering off in'],
]