export const bootLog: (() => string)[] = [
  () => 'AetherOS version 6.1.30 (user@aether-machine) (gcc version 12.2.0) #1 SMP ' + new Date().toUTCString(),
  () => 'Command line: BOOT_IMAGE=/boot/vmlinuz-6.1.30 root=/dev/sda1 ro quiet splash',
  () => 'x86_64: Initializing CPU architecture',
  () => 'Memory: 16384000K/16777216K available (12288K kernel code, 4096K rwdata, 2048K rodata, 8192K init)',
  () => 'Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.1.30 root=/dev/sda1 ro quiet splash',
  () => 'DMI: TSRC Systems/TSRC-One, BIOS TSRC-1.4.5 12/06/2024',
  () => 'Secure Boot: Disabled',
  () => 'Virtualization: VSM support enabled',
  () => 'x86/CPU: VEX-9 HyperCore Architecture detected',
  () => 'x86/CPU: TSRC Celestium™ NX9-4100 @ 3.20GHz (family: 10, model: 49, stepping: 7)',

  () => 'MTRR: Memory Type Range Registers enabled',
  () => 'ACPI: Core revision 20230520',
  () => 'ACPI: Power Button [PWRB]',
  () => 'ACPI: Lid Switch [LID0]',
  () => 'ACPI: Thermal Zone [THRM] (28 C)',
  () => 'PCI: MMCONFIG at [mem 0xe0000000-0xe3ffffff] reserved in region 0',
  () => 'PCI: Probing PCI hardware',
  () => 'PCI: Using host bridge windows from ACPI',
  () => 'Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled',

  () => 'usbcore: registered new interface driver usbfs',
  () => 'usbcore: registered new interface driver hub',
  () => 'usbcore: registered new device driver usb',
  () => 'ehci_hcd: USB 2.0 \'Enhanced\' Host Controller (EHCI) Driver',
  () => 'ohci_hcd: USB 1.1 \'Open\' Host Controller (OHCI) Driver',
  () => 'uhci_hcd: USB Universal Host Controller Interface driver',

  () => 'ata1: SATA link up 6.0 Gbps (SStatus 133 SControl 300)',
  () => 'ata1.00: ATA-12: TSRC QuantaDrive 512G-X, QDX4.02, max UDMA/133',
  () => 'ata1.00: 976773168 sectors, multi 16: LBA48 NCQ (depth 32)',
  () => 'ata1.00: configured for UDMA/133',
  () => 'scsi 0:0:0:0: Direct-Access     TSRC      QuantaDrive 512G-X PQ: 0 ANSI: 5',

  () => 'tsrcgfx 0000:00:02.0: enabling device (0006 -> 0007)',
  () => '[drm] Initialized tsrcgfx 1.6.0 20230520 for 0000:00:02.0 on minor 0',
  () => 'fbcon: tsrcgfxfb (fb0) is primary device',
  () => 'Console: switching to colour frame buffer device 1920x1080',
  () => 'tsrcgfx 0000:00:02.0: fb0: tsrcgfxfb frame buffer device',

  () => 'tsrce-net: TSRC® HyperNet Driver - 1.2.3',
  () => 'tsrce-net: Copyright(c) 2024 TSRC Corporation',
  () => 'tsrce-net 0000:00:19.0: irq 28 for MSI/MSI-X',
  () => 'tsrce-net 0000:00:19.0 eth0: (PCI Express) 44:6a:78:9b:cc:dd',
  () => 'tsrce-net 0000:00:19.0 eth0: TSRC HyperNet Connection',

  () => 'VFS: Mounted root (ext4 filesystem) readonly on device 8:1.',
  () => 'devtmpfs: mounted',
  () => 'Freeing unused kernel memory: 8192K',
  () => 'Write protecting the kernel read-only data: 12288K',
  () => 'Run /sbin/init as init proces',
  () => 'RNG: Initializing hardware random number generator (HWRNG)...',
  () => 'RNG: TSRC QuantaSecure Module detected, entropy pool seeded.',
  () => 'TPM: TSRC TPM 3.0 device initialized (firmware v3.2.1, rev: 17)',
  () => 'PCI: Using ACPI for IRQ routing',
  () => 'TSRC HyperCooling: Initializing advanced thermal management',
  () => 'TSRC HyperCooling: CPU core temps: 34°C, 35°C, 33°C, 36°C',
  () => 'TSRC HyperCooling: GPU temp: 40°C',
  () => 'TSRC HyperCooling: System cooling thresholds set to 75°',

  () => 'NUMA: Node 0/1 available (8 CPUs, 16GB memory)',
  () => 'NUMA: Node distances:\n  Node 0  Node 1  \n 0:  10     20   \n 1:  20     10   ',
  () => 'NUMA: Initializing memory mappings for node 0',
  () => 'NUMA: Initializing memory mappings for node ',

  () => 'scsi 1:0:0:0: Direct-Access     TSRC      QuantaDrive 2TB-P NX PQ: 0 ANSI: 6',
  () => 'sd 1:0:0:0: [sdb] 3907029168 512-byte logical blocks: (2.00 TB/1.82 TiB)',
  () => 'sd 1:0:0:0: [sdb] Write Protect is off',
  () => 'sd 1:0:0:0: [sdb] Mode Sense: 45 00 00 00',
  () => 'sd 1:0:0:0: [sdb] No Caching mode page found',
  () => 'sd 1:0:0:0: [sdb] Assuming drive cache: write through\n sdb: sdb1',
  () => 'sd 1:0:0:0: [sdb] Attached SCSI dis',

  () => 'tsrc-audio: TSRC QuantumSound™ Audio Driver loaded',
  () => 'tsrc-audio: Found QuantumSound™ Wave-X chip, version 1.3',
  () => 'ALSA: Initializing soundcard 0 with 8 output channels, 2 input channels',
  () => 'ALSA: Setting default sample rate to 48kH',
  () => 'tsrce-net 0000:00:19.0 eth0: Link is up - 1Gbps Full Duplex',
  () => 'tsrce-net 0000:00:19.0 eth0: Enabling Jumbo Frames (MTU 9000)',
  () => 'tsrce-net 0000:00:19.0 eth0: IPv6 support enable',
  () => 'tsrcgfx 0000:00:02.0: Enabling ray-tracing extensions',
  () => 'tsrcgfx 0000:00:02.0: HDR support enabled (10-bit color depth)',
  () => 'tsrcgfx 0000:00:02.0: Vulkan API 1.3.2 detected and initialize',

  () => 'usb 1-1: new high-speed USB device number 2 using ehci-pci',
  () => 'usb 1-1: New USB device found, idVendor=1abc, idProduct=1234',
  () => 'usb 1-1: Product: TSRC SecureKey 4.0',
  () => 'usbcore: registered new interface driver usbhid',
  () => 'usbhid: USB HID core drive',

  () => 'systemd[1]: Starting TSRC Power Management...',
  () => 'systemd[1]: Starting Time Synchronization...',
  () => 'systemd[1]: Starting Display Manager...',
  () => 'systemd[1]: Starting Network Time Service...',
  () => 'systemd[1]: Reached target Multi-User System.',
]
export const shutdownLog: (() => string)[] = [
  () => 'Stopping TSRC AI-Assisted Daemon...',
  () => 'Stopping Network Manager...',
  () => 'Stopping Time Synchronization...',
  () => 'Unmounting filesystems...',
  () => 'Saving session state to /var/aether/session-state...',
  () => 'Session state saved successfully.',
  () => 'Stopping Display Manager...',
  () => 'Deactivating TSRC QuantumSound™ Wave-X Audio...',
  () => 'Closing all active audio streams... Done.',
  () => 'Powering down TSRC HyperNet interface (eth0).',
  () => 'Network interface eth0 is now offline.',
  () => 'Disabling Ray-Tracing and HDR on GPU...',
  () => 'TSRC Celestium NX9 GPU has entered low-power mode.',
  () => 'Flushing disk buffers...',
  () => 'All disks safely unmounted.',

  () => 'Stopping remaining user-space services...',
  () => 'Stopping TSRC HyperCooling module...',
  () => 'CPU cores entering idle state...',
  () => 'TSRC Celestium NX9 temperatures: Core 0: 27°C, Core 1: 28°C, GPU: 35°C.',
  () => 'ACPI system state transitioning to S5 (power-off).',

  () => 'Writing final kernel messages to /var/log/aetheros/shutdown.log...',
  () => 'TSRC SecureKey 4.0 removed safely.',
  () => 'Disabling hardware RNG...',
  () => 'Hardware RNG stopped.',
  () => 'TPM module entering secure standby mode...',
  () => 'TPM module status: Standby.',

  () => 'Synchronizing CPU caches...',
  () => 'CPU caches synchronized.',
  () => 'Disabling interrupts...',
  () => 'Shutting down AetherOS kernel subsystems...',

  () => 'System halted. Powering off...\n\nGoodbye from AetherOS. Thank you for trusting TSRC technology.\nPowering off in 3... 2... 1...',
]